version: "3.7"

services:
  sample:
    image: landing_page:1.0
    container_name: landing_page
    build:
      context: "./"
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 8100:8100
    environment:
      - CHOKIDAR_USEPOLLING=true
